import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import './globals.css'
import { library } from '@fortawesome/fontawesome-svg-core';
import { fas } from '@fortawesome/free-solid-svg-icons';
import { config } from '@fortawesome/fontawesome-svg-core'
import '@fortawesome/fontawesome-svg-core/styles.css'
import Navbar from './(Components)/Navbar';
import { getServerSession } from 'next-auth';
// import SessionProvider from '@/utils/SessionProvider';

config.autoAddCss = false
library.add(fas);


const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default async function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  const session = await getServerSession();
  return (
    <html lang="en">
      <body className={inter.className}>
        {/* <SessionProvider session={session}> */}
        <Navbar />
        {children}
        <script src="https://kit.fontawesome.com/9e28ea22be.js" crossOrigin="anonymous"></script>
        {/* </SessionProvider> */}
      </body>
    </html>
  )
}
